sonar.projectKey=java-calculator-app
sonar.projectName=Java Calculator Application
sonar.projectVersion=1.0
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.sourceEncoding=UTF-8
sonar.language=java
sonar.exclusions=**/test/**, **/Dockerfile, **/.gitlab-ci.yml, **/helm/**, **/README.md